//
// RGB color values taken from the following URL:
//
//   https://www.rapidtables.com/web/color/RGB_Color.html
//

//
// R-G-B_values
//
#define RGB_maroon                      0x800000
#define RGB_dark_red                    0x8B0000
#define RGB_brown                       0xA52A2A
#define RGB_fire_brick                  0xB22222
#define RGB_crimson                     0xDC143C
#define RGB_red                         0xFF0000
#define RGB_tomato                      0xFF6347
#define RGB_coral                       0xFF7F50
#define RGB_indian_red                  0xCD5C5C
#define RGB_light_coral                 0xF08080
#define RGB_dark_salmon                 0xE9967A
#define RGB_salmon                      0xFA8072
#define RGB_light_salmon                0xFFA07A
#define RGB_orange_red                  0xFF4500
#define RGB_dark_orange                 0xFF8C00
#define RGB_orange                      0xFFA500
#define RGB_gold                        0xFFD700
#define RGB_dark_golden_rod             0xB8860B
#define RGB_golden_rod                  0xDAA520
#define RGB_pale_golden_rod             0xEEE8AA
#define RGB_dark_khaki                  0xBDB76B
#define RGB_khaki                       0xF0E68C
#define RGB_olive                       0x808000
#define RGB_yellow                      0xFFFF00
#define RGB_yellow_green                0x9ACD32
#define RGB_dark_olive_green            0x556B2F
#define RGB_olive_drab                  0x6B8E23
#define RGB_lawn_green                  0x7CFC00
#define RGB_chart_reuse                 0x7FFF00
#define RGB_green_yellow                0xADFF2F
#define RGB_dark_green                  0x006400
#define RGB_green                       0x008000
#define RGB_forest_green                0x228B22
#define RGB_lime                        0x00FF00
#define RGB_lime_green                  0x32CD32
#define RGB_light_green                 0x90EE90
#define RGB_pale_green                  0x98FB98
#define RGB_dark_sea_green              0x8FBC8F
#define RGB_medium_spring_green         0x00FA9A
#define RGB_spring_green                0x00FF7F
#define RGB_sea_green                   0x2E8B57
#define RGB_medium_aqua_marine          0x66CDAA
#define RGB_medium_sea_green            0x3CB371
#define RGB_light_sea_green             0x20B2AA
#define RGB_dark_slate_Gray             0x2F4F4F
#define RGB_teal                        0x008080
#define RGB_dark_cyan                   0x008B8B
#define RGB_aqua                        0x00FFFF
#define RGB_cyan                        0x00FFFF
#define RGB_light_cyan                  0xE0FFFF
#define RGB_dark_turquoise              0x00CED1
#define RGB_turquoise                   0x40E0D0
#define RGB_medium_turquoise            0x48D1CC
#define RGB_pale_turquoise              0xAFEEEE
#define RGB_aqua_marine                 0x7FFFD4
#define RGB_powder_blue                 0xB0E0E6
#define RGB_cadet_blue                  0x5F9EA0
#define RGB_steel_blue                  0x4682B4
#define RGB_corn_flower_blue            0x6495ED
#define RGB_deep_sky_blue               0x00BFFF
#define RGB_dodger_blue                 0x1E90FF
#define RGB_light_blue                  0xADD8E6
#define RGB_sky_blue                    0x87CEEB
#define RGB_light_sky_blue              0x87CEFA
#define RGB_midnight_blue               0x191970
#define RGB_navy                        0x000080
#define RGB_dark_blue                   0x00008B
#define RGB_medium_blue                 0x0000CD
#define RGB_blue                        0x0000FF
#define RGB_royal_blue                  0x4169E1
#define RGB_blue_violet                 0x8A2BE2
#define RGB_indigo                      0x4B0082
#define RGB_dark_slate_blue             0x483D8B
#define RGB_slate_blue                  0x6A5ACD
#define RGB_medium_slate_blue           0x7B68EE
#define RGB_medium_purple               0x9370DB
#define RGB_dark_magenta                0x8B008B
#define RGB_dark_violet                 0x9400D3
#define RGB_dark_orchid                 0x9932CC
#define RGB_medium_orchid               0xBA55D3
#define RGB_purple                      0x800080
#define RGB_thistle                     0xD8BFD8
#define RGB_plum                        0xDDA0DD
#define RGB_violet                      0xEE82EE
#define RGB_magenta                     0xFF00FF
#define RGB_fuchsia                     0xFF00FF
#define RGB_orchid                      0xDA70D6
#define RGB_medium_violet_red           0xC71585
#define RGB_pale_violet_red             0xDB7093
#define RGB_deep_pink                   0xFF1493
#define RGB_hot_pink                    0xFF69B4
#define RGB_light_pink                  0xFFB6C1
#define RGB_pink                        0xFFC0CB
#define RGB_antique_white               0xFAEBD7
#define RGB_beige                       0xF5F5DC
#define RGB_bisque                      0xFFE4C4
#define RGB_blanched_almond             0xFFEBCD
#define RGB_wheat                       0xF5DEB3
#define RGB_corn_silk                   0xFFF8DC
#define RGB_lemon_chiffon               0xFFFACD
#define RGB_light_golden_rod_yellow     0xFAFAD2
#define RGB_light_yellow                0xFFFFE0
#define RGB_saddle_brown                0x8B4513
#define RGB_sienna                      0xA0522D
#define RGB_chocolate                   0xD2691E
#define RGB_peru                        0xCD853F
#define RGB_sandy_brown                 0xF4A460
#define RGB_burly_wood                  0xDEB887
#define RGB_tan                         0xD2B48C
#define RGB_rosy_brown                  0xBC8F8F
#define RGB_moccasin                    0xFFE4B5
#define RGB_navajo_white                0xFFDEAD
#define RGB_peach_puff                  0xFFDAB9
#define RGB_misty_rose                  0xFFE4E1
#define RGB_lavender_blush              0xFFF0F5
#define RGB_linen                       0xFAF0E6
#define RGB_old_lace                    0xFDF5E6
#define RGB_papaya_whip                 0xFFEFD5
#define RGB_sea_shell                   0xFFF5EE
#define RGB_mint_cream                  0xF5FFFA
#define RGB_slate_Gray                  0x708090
#define RGB_light_slate_Gray            0x778899
#define RGB_light_steel_blue            0xB0C4DE
#define RGB_lavender                    0xE6E6FA
#define RGB_floral_white                0xFFFAF0
#define RGB_alice_blue                  0xF0F8FF
#define RGB_ghost_white                 0xF8F8FF
#define RGB_honeydew                    0xF0FFF0
#define RGB_ivory                       0xFFFFF0
#define RGB_azure                       0xF0FFFF
#define RGB_snow                        0xFFFAFA
#define RGB_black                       0x000000
#define RGB_dim_gray                    0x696969
#define RGB_dim_grey                    0x696969
#define RGB_gray                        0x808080
#define RGB_grey                        0x808080
#define RGB_dark_gray                   0xA9A9A9
#define RGB_dark_grey                   0xA9A9A9
#define RGB_silver                      0xC0C0C0
#define RGB_light_gray                  0xD3D3D3
#define RGB_light_grey                  0xD3D3D3
#define RGB_gainsboro                   0xDCDCDC
#define RGB_white_smoke                 0xF5F5F5
#define RGB_white                       0xFFFFFF



//
// G-R-B_values
//
#define GRB_maroon                      0x008000
#define GRB_dark_red                    0x008B00
#define GRB_brown                       0x2AA52A
#define GRB_fire_brick                  0x22B222
#define GRB_crimson                     0x14DC3C
#define GRB_red                         0x00FF00
#define GRB_tomato                      0x63FF47
#define GRB_coral                       0x7FFF50
#define GRB_indian_red                  0x5CCD5C
#define GRB_light_coral                 0x80F080
#define GRB_dark_salmon                 0x96E97A
#define GRB_salmon                      0x80FA72
#define GRB_light_salmon                0xA0FF7A
#define GRB_orange_red                  0x45FF00
#define GRB_dark_orange                 0x8CFF00
#define GRB_orange                      0xA5FF00
#define GRB_gold                        0xD7FF00
#define GRB_dark_golden_rod             0x86B80B
#define GRB_golden_rod                  0xA5DA20
#define GRB_pale_golden_rod             0xE8EEAA
#define GRB_dark_khaki                  0xB7BD6B
#define GRB_khaki                       0xE6F08C
#define GRB_olive                       0x808000
#define GRB_yellow                      0xFFFF00
#define GRB_yellow_green                0xCD9A32
#define GRB_dark_olive_green            0x6B552F
#define GRB_olive_drab                  0x8E6B23
#define GRB_lawn_green                  0xFC7C00
#define GRB_chart_reuse                 0xFF7F00
#define GRB_green_yellow                0xFFAD2F
#define GRB_dark_green                  0x640000
#define GRB_green                       0x800000
#define GRB_forest_green                0x8B2222
#define GRB_lime                        0xFF0000
#define GRB_lime_green                  0xCD3232
#define GRB_light_green                 0xEE9090
#define GRB_pale_green                  0xFB9898
#define GRB_dark_sea_green              0xBC8F8F
#define GRB_medium_spring_green         0xFA009A
#define GRB_spring_green                0xFF007F
#define GRB_sea_green                   0x8B2E57
#define GRB_medium_aqua_marine          0xCD66AA
#define GRB_medium_sea_green            0xB33C71
#define GRB_light_sea_green             0xB220AA
#define GRB_dark_slate_Gray             0x4F2F4F
#define GRB_teal                        0x800080
#define GRB_dark_cyan                   0x8B008B
#define GRB_aqua                        0xFF00FF
#define GRB_cyan                        0xFFOOFF
#define GRB_light_cyan                  0xFFE0FF
#define GRB_dark_turquoise              0xCE00D1
#define GRB_turquoise                   0xE040D0
#define GRB_medium_turquoise            0xD148CC
#define GRB_pale_turquoise              0xEEAFEE
#define GRB_aqua_marine                 0xFF7FD4
#define GRB_powder_blue                 0xE0B0E6
#define GRB_cadet_blue                  0x9E5FA0
#define GRB_steel_blue                  0x8246B4
#define GRB_corn_flower_blue            0x9564ED
#define GRB_deep_sky_blue               0xBF00FF
#define GRB_dodger_blue                 0x901EFF
#define GRB_light_blue                  0xD8ADE6
#define GRB_sky_blue                    0xCE87EB
#define GRB_light_sky_blue              0xCE87FA
#define GRB_midnight_blue               0x191970
#define GRB_navy                        0x000080
#define GRB_dark_blue                   0x00008B
#define GRB_medium_blue                 0x0000CD
#define GRB_blue                        0x0000FF
#define GRB_royal_blue                  0x6941E1
#define GRB_blue_violet                 0x2B8AE2
#define GRB_indigo                      0x004B82
#define GRB_dark_slate_blue             0x3D488B
#define GRB_slate_blue                  0x5A6ACD
#define GRB_medium_slate_blue           0x687BEE
#define GRB_medium_purple               0x7093DB
#define GRB_dark_magenta                0x008B8B
#define GRB_dark_violet                 0x0094D3
#define GRB_dark_orchid                 0x3299CC
#define GRB_medium_orchid               0x55BAD3
#define GRB_purple                      0x008080
#define GRB_thistle                     0xBFD8D8
#define GRB_plum                        0xA0DDDD
#define GRB_violet                      0x82EEEE
#define GRB_magenta                     0x00FFFF
#define GRB_fuchsia                     0x00FFFF
#define GRB_orchid                      0x70DAD6
#define GRB_medium_violet_red           0x15C785
#define GRB_pale_violet_red             0x70DB93
#define GRB_deep_pink                   0x14FF93
#define GRB_hot_pink                    0x69FFB4
#define GRB_light_pink                  0xB6FFC1
#define GRB_pink                        0xC0FFCB
#define GRB_antique_white               0xEBFAD7
#define GRB_beige                       0xF5F5DC
#define GRB_bisque                      0xE4FFC4
#define GRB_blanched_almond             0xEBFFCD
#define GRB_wheat                       0xDEF5B3
#define GRB_corn_silk                   0xF8FFDC
#define GRB_lemon_chiffon               0xFAFFCD
#define GRB_light_golden_rod_yellow     0xFAFAD2
#define GRB_light_yellow                0xFFFFE0
#define GRB_saddle_brown                0x458B13
#define GRB_sienna                      0x52A02D
#define GRB_chocolate                   0x69D21E
#define GRB_peru                        0x85CD3F
#define GRB_sandy_brown                 0xA4F460
#define GRB_burly_wood                  0xB8DE87
#define GRB_tan                         0xB4D28C
#define GRB_rosy_brown                  0x8FBC8F
#define GRB_moccasin                    0xE4FFB5
#define GRB_navajo_white                0xDEFFAD
#define GRB_peach_puff                  0xDAFFB9
#define GRB_misty_rose                  0xE4FFE1
#define GRB_lavender_blush              0xF0FFF5
#define GRB_linen                       0xF0FAE6
#define GRB_old_lace                    0xF5FDE6
#define GRB_papaya_whip                 0xEFFFD5
#define GRB_sea_shell                   0xF5FFEE
#define GRB_mint_cream                  0xFFF5FA
#define GRB_slate_Gray                  0x807090
#define GRB_light_slate_Gray            0x887799
#define GRB_light_steel_blue            0xC4B0DE
#define GRB_lavender                    0xE6E6FA
#define GRB_floral_white                0xFAFFF0
#define GRB_alice_blue                  0xF8F0FF
#define GRB_ghost_white                 0xF8F8FF
#define GRB_honeydew                    0xFFF0F0
#define GRB_ivory                       0xFFFFF0
#define GRB_azure                       0xFFF0FF
#define GRB_snow                        0xFAFFFA
#define GRB_black                       0x000000
#define GRB_dim_Gray                    0x696969
#define GRB_dim_Grey                    0x696969
#define GRB_gray                        0x808080
#define GRB_grey                        0x808080
#define GRB_dark_Gray                   0xA9A9A9
#define GRB_dark_Grey                   0xA9A9A9
#define GRB_silver                      0xC0C0C0
#define GRB_light_Gray                  0xD3D3D3
#define GRB_light_Grey                  0xD3D3D3
#define GRB_gainsboro                   0xDCDCDC
#define GRB_white_smoke                 0xF5F5F5
#define GRB_white                       0xFFFFFF
